### PR TITLE
Add buildFractionalSendTx to specify decimal points

### PR DESCRIPTION
**Pull request by ethanfrey**
a new method that takes whole and fractional.
fractional is specified in steps of 10^-9.

That is a value of `0.001` would be fractional = `1000000`

### CODE REVIEW

**Comment by pavlealeksic** [comment]
Is there any reason why we need 2 functions for sending the transactions, because we can go with just splitting the number with . so we would get both whole and fractional(if existing) and add it onto the same transaction function?

**Comment by ethanfrey** [comment]
Two reasons:

1. I didn't want to change the interface, so I provide a new function so I can do the separate whole and fractional.
2. There is worry about rounding issues, so we force the client to use integers.. this is a design decision that @Isabello feels strongly about.

I do see your point though. How about I leave the new one as an "exact" way to specify number (no float rounding), and update the existing one to calculate the fractional part as well, if you don't mind rounding.

This way your code will "just work", and you can update it later if you want to parse it better.
(I mean, you can take user input as a string, split on "." and then calculate the exact fractional amount with no rounding issues). But for usability I will add the simple case also.

**Comment by ethanfrey** [comment]
Okay, I updated buildSendTx to perform as you requested. It was actually a bit harder than I thought, good I did it in weave-js to unit test it.

Let me know if this is good for you now.

**Comment by pavlealeksic** [comment]
Yeah this seems simpler, and it will work properly from what I see

**Comment by rudi-cilibrasi** [comment]
in another pr we think we should add `decimals` parameter instead of assuming 9 assert it is 9.

**Pull request merged**
